import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const browser=await chromium.launch({headless:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:8787/#map');
 await expect(page.locator('nav a[href="#map"]')).toHaveText('Оперативная карта');
 await expect(page.locator('main h1')).toHaveText('Оперативная карта');
 await expect(page.locator('.crumb strong')).toHaveText('Оперативная карта');
 await expect(page).toHaveTitle('Оперативная карта · JibekJoly');
 assert.equal(await page.locator('nav a').count(),13);
 await expect(page.locator('#world canvas')).toBeVisible();
 const stats=await page.locator('#live-stats').innerText(),trains=await page.locator('#train-table').innerText();
 await page.getByRole('button',{name:'2D Диспетчерская схема',exact:true}).click();
 await expect(page.locator('.dispatcher-scheme')).toBeVisible();
 assert.equal(await page.locator('#world').count(),0);
 assert.equal(await page.locator('[data-station-id]').count(),9);
 assert.equal(await page.locator('.scheme-train').count(),6);
 assert.equal(await page.locator('#live-stats').innerText(),stats);
 assert.equal(await page.locator('#train-table').innerText(),trains);
 await page.locator('.scheme-train[data-id="SIM-FRT-209"] rect').click();
 await expect(page.locator('.scheme-train[data-id="SIM-FRT-209"]')).toHaveClass(/selected/);
 await page.locator('[data-station-id="team-station-4"] rect').click();
 await expect(page.locator('#modal-title')).toHaveText('Қарағанды');
 await page.getByRole('button',{name:'Закрыть',exact:true}).click();
 const signal=page.locator('.dispatcher-scheme [data-act="signal"][data-id="0"][data-dir="1"]');
 await signal.click();await expect(signal).toHaveAttribute('aria-label',/red$/);
 await signal.click();await expect(signal).toHaveAttribute('aria-label',/green$/);
 await page.locator('#play-button').click();await page.waitForTimeout(400);await page.locator('#play-button').click();
 // Refresh the existing 200 ms display cadence after pausing before comparing.
 await page.locator('.scheme-train[data-id="SIM-FRT-209"] rect').click();
 const liveTrains=await page.locator('#train-table').innerText(),liveStats=await page.locator('#live-stats').innerText();
 await page.getByRole('button',{name:'3D Обзор сети',exact:true}).click();
 await expect(page.locator('#world canvas')).toBeVisible();
 assert.equal(await page.locator('#train-table').innerText(),liveTrains);assert.equal(await page.locator('#live-stats').innerText(),liveStats);
 await page.getByRole('button',{name:'2D Диспетчерская схема',exact:true}).click();
 await page.getByRole('button',{name:'KZ',exact:true}).click();
 await expect(page.locator('main h1')).toHaveText('Операциялық карта');
 await expect(page).toHaveTitle('Операциялық карта · JibekJoly');
 await expect(page.getByRole('button',{name:'2D Диспетчерлік схема',exact:true})).toHaveAttribute('aria-pressed','true');
 await page.getByRole('button',{name:'RU',exact:true}).click();
 await page.getByRole('button',{name:'Следовать камерой',exact:true}).click();
 await expect(page.locator('#world canvas')).toBeVisible();
 await page.getByRole('button',{name:'2D Диспетчерская схема',exact:true}).click();
 await page.locator('nav a[href="#dashboard"]').click();
 await expect(page.locator('main a[href="#map"]')).toHaveText('Оперативная карта');
 await page.locator('nav a[href="#map"]').click();
 await expect(page.getByRole('button',{name:'2D Диспетчерская схема',exact:true})).toHaveAttribute('aria-pressed','true');
 await page.getByRole('button',{name:'Сменить тему',exact:true}).click();
 await expect(page.locator('.dispatcher-scheme')).toBeVisible();
 fs.mkdirSync('.jol-local/review',{recursive:true});await page.screenshot({path:'.jol-local/review/operations-map-2d.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 assert.deepEqual(errors,[]);
 console.log('PASS: Operations Map names RU/KK, same state/index in 3D↔2D, nine canonical stations, six trains, selection, station arrivals, signals, live updates, theme and mobile');
}finally{await browser.close()}
