import {Miniflare} from 'miniflare';import fs from 'node:fs';import assert from 'node:assert/strict';
const mf=new Miniflare({modules:true,scriptPath:'dist/server/index.js',compatibilityDate:'2025-09-01',d1Databases:['DB'],bindings:{ADMIN_EMAIL:'admin@example.test'}});
const db=await mf.getD1Database('DB');for(const sql of fs.readFileSync('drizzle/0000_chief_black_bolt.sql','utf8').split('--> statement-breakpoint').filter(s=>s.trim()))await db.prepare(sql.trim()).run();
const url='http://localhost',head=(id,email)=>({'origin':url,'content-type':'application/json',...(id?{'oai-authenticated-user-id':id,'oai-authenticated-user-email':email}: {})});
const fetcher=(p,method='GET',data=null,id=null,email='viewer@example.test')=>mf.dispatchFetch(url+p,{method,headers:head(id,email),...(data?{body:JSON.stringify(data)}:{})});
try{
assert.equal((await fetcher('/')).status,200);assert.equal((await fetcher('/app.js')).status,200);assert.equal((await fetcher('/api/health')).status,200);
const pkg=await (await fetcher('/eco/package')).json();assert.equal(pkg.package_id,'kz-eco-synthetic-v2');assert.equal(pkg.synthetic_only,true);
const advice=await fetcher('/eco/advice','POST',{train_id:'SIM-FRT-208',distance_km:7,current_speed_kmh:80,speed_limit_kmh:80,now_min:0,signal_open_min:10,mass_tons:3500});assert.equal(advice.status,200);const calculated=await advice.json();assert.equal(calculated.recommended_speed_kmh,42);assert(calculated.cruise_speed_kmh<42);assert.equal(calculated.recommended_speed_profile[0].speed_kmh,80);
assert.equal((await fetcher('/eco/advice','POST',{train_id:'SIM-FRT-208',distance_km:-1})).status,422);
const config=await (await fetcher('/api/settings')).json();assert.equal((await fetcher('/api/settings','PUT',config)).status,401);assert.equal((await fetcher('/api/settings','PUT',config,'user')).status,403);assert.equal((await fetcher('/api/settings','PUT',{...config,normal:10,critical:40},'admin','admin@example.test')).status,400);assert.equal((await fetcher('/api/settings','PUT',config,'admin','admin@example.test')).status,200);
const s=await (await fetcher('/api/sessions','POST',{},'user')).json();assert(s.id);assert.equal((await fetcher('/api/history?session='+s.id,'GET',null,'different')).status,404);
let r=await fetcher('/api/command','POST',{session:s.id,kind:'incident'},'user');assert.equal(r.status,200);let w=(await r.json()).world;assert.equal(w.incidents.length,1);assert(w.lastPlan.ms<5000);assert.equal(w.lastPlan.alternatives.length,6);
r=await fetcher('/api/history?session='+s.id,'GET',null,'user');const initial=await r.json();assert.equal(initial[0].time,0);assert(initial.length>=1);assert.equal(initial.at(-1).world.incidents.length,1);
assert.equal((await fetcher('/api/command','POST',{session:s.id,kind:'play'},'different')).status,404);
await fetcher('/api/command','POST',{session:s.id,kind:'play'},'user');
const response=await fetcher('/api/stream?session='+s.id,'GET',null,'user');assert.equal(response.headers.get('content-type'),'text/event-stream');const reader=response.body.getReader();let text='',start=Date.now();while((text.match(/event: telemetry/g)||[]).length<3&&Date.now()-start<5000){text+=new TextDecoder().decode((await reader.read()).value);}await reader.cancel();const packets=text.split('\n').filter(l=>l.startsWith('data: ')).map(l=>JSON.parse(l.slice(6)));assert(packets.length>=3);assert.equal(packets[0].positions.length,6);assert.equal(packets[0].signals.length,16);assert(packets.at(-1).modelTime>packets[0].modelTime);console.log('SSE:',packets.length,'packets in',Date.now()-start,'ms; six positions, sixteen directional signals; world advances.');
const complete=JSON.parse(fs.readFileSync('web/demo-trip.json','utf8'));const saved=await (await fetcher('/api/sessions','POST',{world:complete},'user')).json();assert(saved.id);const full=await(await fetcher('/api/history?session='+saved.id,'GET',null,'user')).json();assert.equal(full[0].time,0);assert(full.length>180);assert(full.at(-1).world.done);const reopened=await(await fetcher('/api/trip?session='+saved.id,'GET',null,'user')).json();assert.equal(reopened.world.timeline.length,complete.timeline.length);assert.equal((await fetcher('/api/trip?session='+saved.id,'GET',null,'different')).status,404);console.log('Full trip persisted and reopened:',full.length,'frames starting at zero, ending at',full.at(-1).time);
const spec=await(await fetcher('/api/openapi.json')).json();assert.equal(spec.openapi,'3.0.3');assert(spec.paths['/api/history']);assert(spec.paths['/eco/advice']);assert(spec.components.schemas.EcoRequest);
console.log('PASS: Worker assets, D1 migrations, settings 401/403/400/200, owner isolation, six-policy replanning, saved history, 1 Hz SSE, OpenAPI.');
assert(spec.paths['/api/extension/state']);assert(spec.paths['/api/extension/resources/yard/apply']);
assert.equal((await fetcher('/api/extension/state')).status,401);
assert.equal((await fetcher('/api/extension/state','GET',null,'user')).status,503);
console.log('PASS: extension OpenAPI namespace, sign-in guard and explicit unavailable-service response.');
}finally{await mf.dispose();}
