import {adviceFromSnapshot,ecoPaths,ecoRequestSchema} from './eco-api.js';
import {syntheticData} from '../web/synthetic-data.js';
import {tripSamples,recordFrame} from '../web/journey.js';
import assets from './assets.generated.json';
import {makeWorld,step,action,trigger,assertWorld,incidentFor,signalState} from '../web/corridor-engine.js';
import {defaultConfig,validateConfig,quality} from '../web/quality.js';
import {forecast,applyPolicy,policies} from '../web/planning.js';
const json=(data,status=200)=>Response.json(data,{status,headers:{'cache-control':'no-store'}});
const db=env=>{if(!env.DB)throw Error('Storage unavailable');return env.DB;};
const user=req=>({id:req.headers.get('oai-authenticated-user-id'),email:req.headers.get('oai-authenticated-user-email')});
const role=(u,env)=>u.id?(u.email&&env.ADMIN_EMAIL&&u.email.toLowerCase()===env.ADMIN_EMAIL.toLowerCase()?'admin':'viewer'):'anonymous';
const fail=(code,message)=>{throw Object.assign(Error(message),{status:code});};
const auth=req=>{const u=user(req);if(!u.id)fail(401,'Войдите через ChatGPT / ChatGPT арқылы кіріңіз');return u;};
const clean=w=>({...w,log:w.log.slice(0,180)});
async function config(env){const row=await db(env).prepare('SELECT value FROM settings WHERE id = ?').bind('quality').first();return row?JSON.parse(row.value):defaultConfig;}
async function owned(req,env,id){const u=auth(req);const row=await db(env).prepare('SELECT * FROM sessions WHERE id = ? AND owner = ? AND updated >= ?').bind(id||'',u.id,Date.now()-72*3600000).first();if(!row)fail(404,'Session not found');return row;}
async function body(req){const s=await req.text();if(s.length>1500000)fail(413,'Payload too large');try{return JSON.parse(s);}catch{fail(400,'Invalid JSON');}}
function validateWorld(w){if(!w||!Array.isArray(w.trains)||w.trains.length!==6||!Array.isArray(w.blocks)||w.blocks.length!==8||!Array.isArray(w.history)||w.history.length>500||!Array.isArray(w.log)||w.log.length>200||(w.timeline&&(!Array.isArray(w.timeline)||w.timeline.length>1100))||!Array.isArray(w.incidents)||w.incidents.length>20||!Number.isFinite(w.time)||w.time<0||w.time>500)fail(400,'Invalid simulation');try{assertWorld(w);}catch{fail(400,'Invalid occupancy');}return clean(w);}
async function saveSample(env,row,w){const now=Date.now();await db(env).batch([db(env).prepare('INSERT INTO samples (id, session, owner, model_time, state, created) VALUES (?, ?, ?, ?, ?, ?)').bind(crypto.randomUUID(),row.id,row.owner,w.time,JSON.stringify({...clean(w),timeline:[],history:[]}),now),db(env).prepare('DELETE FROM samples WHERE created < ?').bind(now-72*3600000),db(env).prepare('DELETE FROM sessions WHERE updated < ?').bind(now-72*3600000)]);}
export function envelope(w,seq){return {schema:'jol.telemetry.v1',sequence:seq,sentAt:Date.now(),source:'simulator',modelTime:w.time,positions:w.trains.map(t=>({trainId:t.id,block:t.segment,station:t.node,progress:t.p,direction:t.dir,lane:t.lane,speed:t.state==='running'?(t.actualSpeed||0):0,delay:t.delay})),signals:w.blocks.flatMap(b=>[1,-1].map(dir=>{const s=signalState(w,b.i,dir);return {block:b.i,direction:dir,id:s.id,aspect:s.aspect,opensAt:s.opensAt,occupant:b[s.lane]};})),switches:w.blocks.map(b=>({block:b.i,reserveOpen:b.reserveOpen,occupant:b.reserve})),timetable:w.trains.map(t=>({trainId:t.id,plannedArrival:t.plan,actualArrival:t.finished})),world:clean(w),quality:quality(w)};}
function autoPlan(w){const p=forecast(w,w.config||defaultConfig);if(p.valid){applyPolicy(w,policies.find(x=>x.id===p.best));w.lastPlan={ms:p.ms,best:p.best,at:w.time,version:(w.lastPlan?.version||0)+1,alternatives:p.candidates.map(x=>({id:x.policy.id,index:x.quality.index,delay:x.metrics.total,valid:x.valid}))};}}
function stream(req,env,row,c){let timer,closed=false,seq=0,busy=false,w=row?JSON.parse(row.state):makeWorld();w.config=c;const enc=new TextEncoder();const readable=new ReadableStream({async start(controller){const tick=async()=>{if(closed||busy)return;busy=true;try{if(seq%5===0)c=await config(env);if(row){row=await db(env).prepare('SELECT * FROM sessions WHERE id = ? AND owner = ?').bind(row.id,row.owner).first();if(!row)throw Error('Session expired');w=JSON.parse(row.state);w.config=c;if(row.running&&Date.now()-row.updated>=900){const events=step(w,1);if(events.length)autoPlan(w);const now=Date.now();const result=await db(env).prepare('UPDATE sessions SET state = ?, updated = ?, running = ?, version = version + 1 WHERE id = ? AND version = ?').bind(JSON.stringify(clean(w)),now,w.done?0:1,row.id,row.version).run();if(result.meta.changes&&seq%5===0)await saveSample(env,row,w);}}else{const events=step(w,1);if(events.length)autoPlan(w);}controller.enqueue(enc.encode('id: '+(++seq)+'\nevent: telemetry\ndata: '+JSON.stringify(envelope(w,seq))+'\n\n'));}catch(e){controller.enqueue(enc.encode('event: fault\ndata: '+JSON.stringify({error:'Поток недоступен. Переподключитесь.'})+'\n\n'));}finally{busy=false;}};await tick();if(!closed)timer=setInterval(tick,1000);req.signal.addEventListener('abort',()=>{closed=true;clearInterval(timer);try{controller.close();}catch{}},{once:true});},cancel(){closed=true;clearInterval(timer);}});return new Response(readable,{headers:{'content-type':'text/event-stream','cache-control':'no-cache, no-transform','x-accel-buffering':'no'}});}
const paths={
...ecoPaths,
'/api/session':{get:{summary:'Verified session and role',responses:{200:{description:'User role; anonymous allowed'}}}},
'/api/settings':{get:{summary:'Quality weights and optimization priorities',responses:{200:{description:'Runtime configuration'}}},put:{summary:'Update configuration (admin only)',requestBody:{required:true,content:{'application/json':{schema:{$ref:'#/components/schemas/Config'}}}},responses:{200:{description:'Saved'},401:{description:'Sign in required'},403:{description:'Admin only'},400:{description:'Invalid weights or thresholds'}}}},
'/api/stream':{get:{summary:'1 Hz simulated positions, signals, switches and timetable via SSE',parameters:[{name:'session',in:'query',schema:{type:'string'},description:'Omit for public read-only demo; owner session otherwise'}],responses:{200:{description:'text/event-stream; telemetry and fault events'}}}},
'/api/sessions':{get:{summary:'Own sessions from last 72 hours',responses:{200:{description:'Sessions'}}},post:{summary:'Create owner-scoped simulation',responses:{201:{description:'Session ID'},401:{description:'Authentication required'}}}},
'/api/command':{post:{summary:'Apply command to own simulation',requestBody:{content:{'application/json':{schema:{type:'object',required:['session','kind'],properties:{session:{type:'string'},kind:{enum:['play','pause','reset','incident','repair','reserve','priority','hold','wait','policy']},train:{type:'string'},block:{type:'integer',minimum:0,maximum:7},policy:{type:'string'}}}}}},responses:{200:{description:'Updated world'},409:{description:'Concurrent update; refresh'},401:{description:'Authentication required'}}}},
'/api/trip':{get:{summary:'Complete saved trip including speed timeline',parameters:[{name:'session',in:'query',required:true,schema:{type:'string'}}],responses:{200:{description:'World with full timeline'},404:{description:'Not owned'}}}},
'/api/history':{get:{summary:'Complete trip frames from departure; owner only; retention 72 h',parameters:[{name:'session',in:'query',required:true,schema:{type:'string'}}],responses:{200:{description:'Snapshots oldest to newest'},404:{description:'Session inaccessible'}}}},
'/api/snapshots':{post:{summary:'Save local simulation to own session (max one sample / 4 seconds)',responses:{200:{description:'Saved'},429:{description:'Rate limit'},400:{description:'Invalid simulation'}}}},
'/api/health':{get:{summary:'Storage health',responses:{200:{description:'Healthy'},503:{description:'Unavailable'}}}}
};
export const openapi={openapi:'3.0.3',info:{title:'JOL Digital Station API',version:'3.0.0',description:'Demonstration data only. Model minutes and compressed topology. Authentication is provided by trusted platform headers; clients must not supply identity headers.'},paths,components:{schemas:{EcoRequest:ecoRequestSchema,Config:{type:'object',required:['weights','normal','critical','priorities'],properties:{weights:{type:'array',minItems:5,maxItems:5,items:{type:'number',minimum:0,maximum:100}},normal:{type:'number'},critical:{type:'number'},priorities:{type:'array',minItems:3,maxItems:3,items:{type:'number',minimum:1,maximum:10}}}}}}};
export default {async fetch(req,env){const u=new URL(req.url),path=u.pathname;try{if(path==='/eco/package'&&req.method==='GET')return json(syntheticData);if(path==='/eco/advice'&&req.method==='POST'){if(req.headers.get('origin')!==u.origin)fail(403,'Same-origin requests only');return json(adviceFromSnapshot(await body(req)));}if(path.startsWith('/api/')){if(!['GET','HEAD'].includes(req.method)&&req.headers.get('origin')!==u.origin)fail(403,'Same-origin requests only');if(path==='/api/openapi.json')return json(openapi);if(path==='/api/session')return json({signedIn:!!user(req).id,role:role(user(req),env)});if(path==='/api/health'){await db(env).prepare('SELECT 1 AS ok').first();return json({ok:true,retentionHours:72,streamHz:1});}if(path==='/api/settings'){if(req.method==='PUT'){const person=auth(req);if(role(person,env)!=='admin')fail(403,'Настройки доступны администратору / Тек әкімшіге қолжетімді');let c;try{c=validateConfig(await body(req));}catch{fail(400,'Проверьте веса и пороги / Салмақтар мен шектерді тексеріңіз');}await db(env).prepare('INSERT INTO settings (id,value,updated) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value,updated=excluded.updated').bind('quality',JSON.stringify(c),Date.now()).run();return json(c);}return json(await config(env));}
if(path==='/api/sessions'){const person=auth(req);if(req.method==='POST'){const b=await body(req),id=crypto.randomUUID(),w=b.world?validateWorld(b.world):makeWorld();w.config=await config(env);await db(env).prepare('INSERT INTO sessions (id,owner,state,updated) VALUES (?,?,?,?)').bind(id,person.id,JSON.stringify(w),Date.now()).run();return json({id,world:w},201);}const r=await db(env).prepare('SELECT id,updated FROM sessions WHERE owner = ? AND updated >= ? ORDER BY updated DESC LIMIT 30').bind(person.id,Date.now()-72*3600000).all();return json(r.results);}
if(path==='/api/stream'){const row=u.searchParams.has('session')?await owned(req,env,u.searchParams.get('session')):null;return stream(req,env,row,await config(env));}
if(path==='/api/trip'){const row=await owned(req,env,u.searchParams.get('session'));return json({world:JSON.parse(row.state),updated:row.updated});}
if(path==='/api/history'){const row=await owned(req,env,u.searchParams.get('session'));const saved=JSON.parse(row.state);if(saved.timeline?.length)return json(tripSamples(saved));const r=await db(env).prepare('SELECT model_time, state, created FROM samples WHERE session = ? AND owner = ? AND created >= ? ORDER BY created DESC').bind(row.id,row.owner,Date.now()-72*3600000).all();return json(r.results.reverse().map(r=>({time:r.model_time,created:r.created,world:JSON.parse(r.state)})));}
if(path==='/api/snapshots'&&req.method==='POST'){const b=await body(req),row=await owned(req,env,b.session);if(Date.now()-row.updated<4000)fail(429,'Save every 5 seconds');const w=validateWorld(b.world);await db(env).prepare('UPDATE sessions SET state = ?, updated = ?, version = version + 1 WHERE id = ? AND owner = ?').bind(JSON.stringify(w),Date.now(),row.id,row.owner).run();await saveSample(env,row,w);return json({saved:true});}
if(path==='/api/command'&&req.method==='POST'){const b=await body(req),row=await owned(req,env,b.session),w=JSON.parse(row.state);w.config=await config(env);let running=row.running;switch(b.kind){case'play':running=1;break;case'pause':running=0;break;case'reset':Object.assign(w,makeWorld());running=0;break;case'incident':{if(w.triggered.length>=4)fail(400,'All incidents already generated');const e=trigger(w,w.triggered.length);if(e)autoPlan(w);break;}case'policy':{const p=policies.find(p=>p.id===b.policy);if(!p)fail(400,'Unknown policy');applyPolicy(w,p);break;}default:if(!['repair','reserve','priority','hold','wait'].includes(b.kind)||!Number.isInteger(b.block)||b.block<0||b.block>7||!action(w,b.kind,b.train,b.block))fail(400,'Command unavailable');}recordFrame(w,true);const r=await db(env).prepare('UPDATE sessions SET state = ?, running = ?, updated = ?, version = version + 1 WHERE id = ? AND owner = ? AND version = ?').bind(JSON.stringify(clean(w)),running,Date.now(),row.id,row.owner,row.version).run();if(!r.meta.changes)fail(409,'State changed; retry');await saveSample(env,row,w);return json({world:w,running:!!running});}
return json({error:'Not found'},404);}
if(!['GET','HEAD'].includes(req.method))return new Response('Method not allowed',{status:405});const key=path==='/'?'/index.html':path;const a=assets[key];if(!a)return new Response('Not found',{status:404});const bytes=Uint8Array.from(atob(a.body),c=>c.charCodeAt(0));return new Response(req.method==='HEAD'?null:bytes,{headers:{'content-type':a.type,'cache-control':key.includes('/vendor/')?'public,max-age=86400':'no-cache','x-content-type-options':'nosniff'}});
}catch(e){if(!e.status)console.error('JOL request failed',path,e.message);return json({error:e.status?e.message:'Сервис временно недоступен. Повторите запрос. / Сервис уақытша қолжетімсіз.'},e.status||503);}}};
