import {t as tr} from './i18n';
import {useState} from 'react';
import {ArrowUpRight,X,TrainFront,ZoomIn,ZoomOut} from 'lucide-react';
import type {Snapshot,Train,Visit} from './types';
import {clock,label,minutes} from './services';

export const trainColor=(t:Train)=>t.upcoming_conflicts.length?'#c55749':t.delay_seconds>=300?'#b57d2f':t.delay_seconds>=60?'#c49b5c':t.type==='express'?'#477cba':t.type==='passenger'?'#398e8b':'#a38455';

export function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}

export function Panel({title,subtitle,action,children,className=''}:{title:string;subtitle?:string;action?:React.ReactNode;children:React.ReactNode;className?:string}){return <section className={`panel ${className}`}><header className="panel-head"><div><h2>{tr(title)}</h2>{subtitle&&<p>{tr(subtitle)}</p>}</div>{action}</header>{children}</section>}

export function Network({state,onSelect,compact=false}:{state:Snapshot;onSelect:(id:string)=>void;compact?:boolean}){
 const x=(km:number)=>62+km/164*956;
 return <div className={`network ${compact?'compact':''}`}><svg viewBox="0 0 1080 330" role="img" aria-label={tr("Railway topology with live train positions")}>
  <defs><pattern id="grid" width="24" height="24" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".65" fill="#dae1e5"/></pattern></defs><rect width="1080" height="330" fill="url(#grid)"/>
  <text x="32" y="32" className="svg-eyebrow">{tr("ARQA — DALA CORRIDOR")}</text><text x="1045" y="32" textAnchor="end" className="svg-small">{tr("164.0 KM · SYNTHETIC NETWORK")}</text>
  {state.blocks.map(b=>{const a=x(b.start_km),z=x(b.end_km),color=b.status==='closed'?'#c55749':b.status==='occupied'?'#398e8b':b.status==='restricted'?'#bd892e':'#aab9c4';return <g key={b.id}><title>{b.id} · {b.track_type} · {b.status} · {b.speed_limit_kmh} {tr("km/h")}</title><line x1={a} x2={z} y1={164} y2={164} stroke={color} strokeWidth={b.status==='occupied'?5:3} strokeDasharray={b.status==='closed'?'7 4':undefined}/>{b.track_type==='double'&&<line x1={a} x2={z} y1={174} y2={174} stroke={color} strokeWidth="2"/>}<text x={(a+z)/2} y={207} textAnchor="middle" className="svg-mono">{b.id}</text>{!compact&&<text x={(a+z)/2} y={226} textAnchor="middle" className="svg-small">{b.speed_limit_kmh} {tr("km/h")}</text>}{b.status==='closed'&&<text x={(a+z)/2} y={150} textAnchor="middle" fill="#c55749" fontSize="16">{tr("× CLOSED")}</text>}</g>})}
  {state.stations.map(s=><g key={s.id}>{s.siding_available&&<><path d={`M ${x(s.distance_km)-28} 164 l 12 -28 h 32 l 12 28`} fill="none" stroke="#aab9c4" strokeWidth="2"/><text x={x(s.distance_km)} y="119" textAnchor="middle" className="svg-small">{tr("SIDING")}</text></>}<rect x={x(s.distance_km)-5} y="157" width="10" height="26" rx="2" fill="#f8fafb" stroke="#263e4d" strokeWidth="2"/><text x={x(s.distance_km)} y="264" textAnchor="middle" className="svg-mono">{s.id}</text><text x={x(s.distance_km)} y="283" textAnchor="middle" className="svg-station">{tr(s.name)}</text><text x={x(s.distance_km)} y="301" textAnchor="middle" className="svg-small">{s.distance_km} {tr("km")}</text></g>)}
  {state.signals.filter(s=>s.direction===1).map(s=>{const b=state.blocks.find(b=>b.id===s.block_id)!;return <g key={s.id}><line x1={x(b.end_km)-8} x2={x(b.end_km)-8} y1="185" y2="195" stroke="#aab9c4"/><circle cx={x(b.end_km)-8} cy="189" r="3" fill={s.status==='green'?'#4a9984':s.status==='red'?'#c55749':'#858f96'}/></g>})}
  {state.trains.filter(t=>t.status!=='scheduled'&&t.status!=='completed').map((t,i)=>{const px=x(t.distance_km),y=t.direction===1?65+(i%3)*22:235-(i%3)*22;return <g key={t.id} onClick={()=>onSelect(t.id)} onKeyDown={e=>{if(e.key==='Enter')onSelect(t.id)}} tabIndex={0} role="button" aria-label={`Select ${t.id}`} className="train-symbol"><title>{t.id} · {t.speed_kmh} {tr("km/h · +")}{minutes(t.delay_seconds)}</title><line x1={px} x2={px} y1={y+13} y2={160} stroke={trainColor(t)} strokeWidth="1" strokeDasharray="2 3" opacity=".4"/><rect x={px-28} y={y-1} width="56" height="20" rx="3" fill={trainColor(t)}/><text x={px} y={y+13} textAnchor="middle" fill="white" fontSize="11" fontFamily="monospace">{t.id} {t.direction===1?'›':'‹'}</text></g>})}
 </svg><div className="legend"><span><i className="dot teal"/>{tr("Occupied")}</span><span><i className="dot gray"/>{tr("Available")}</span><span><i className="dot amber"/>{tr("Restricted")}</span><span><i className="dot red"/>{tr("Closed / conflict")}</span><span className="legend-tail">{tr("Click a service to inspect")}<ArrowUpRight size={12}/></span></div></div>
}

export function Diagram({state,onSelect,selected,preview,range=3600,filter='all'}:{state:Snapshot;onSelect:(id:string)=>void;selected?:string;preview?:Visit[];range?:number;filter?:string}){
 const [zoom,setZoom]=useState(1),[pan,setPan]=useState(0),[hover,setHover]=useState('');
 const start=state.time-600+pan,end=start+range/zoom;
 const x=(time:number)=>95+(time-start)/(end-start)*925,y=(km:number)=>50+km/164*370;
 const path=(visits:Visit[])=>visits.flatMap(v=>[`${x(v.start)},${y(v.from_km)}`,`${x(v.end)},${y(v.to_km)}`]).join(' ');
 const trains=state.trains.filter(t=>filter==='all'||t.type===filter||(filter==='delayed'&&t.delay_seconds>0)||(filter==='conflicting'&&t.upcoming_conflicts.length));
 return <div className="diagram"><div className="chart-toolbar"><div className="legend"><span><i className="line dashed"/>{tr("Original timetable")}</span><span><i className="line"/>{tr("Actual movement")}</span><span><i className="line teal"/>{tr("Recommended")}</span><span><i className="dot red"/>{tr("Conflict")}</span></div><div className="button-group"><button aria-label={tr("Pan earlier")} onClick={()=>setPan(p=>p-300)}>←</button><button aria-label={tr("Zoom out")} onClick={()=>setZoom(z=>Math.max(1,z/1.5))}><ZoomOut size={15}/></button><button aria-label={tr("Zoom in")} onClick={()=>setZoom(z=>Math.min(4,z*1.5))}><ZoomIn size={15}/></button><button aria-label={tr("Pan later")} onClick={()=>setPan(p=>p+300)}>→</button></div></div>
 <svg viewBox="0 0 1080 490" role="img" aria-label={tr("Train time-distance diagram")}><defs><clipPath id="diagram-clip"><rect x="95" y="40" width="925" height="390"/></clipPath></defs>
 {state.stations.map(s=><g key={s.id}><line x1="95" x2="1020" y1={y(s.distance_km)} y2={y(s.distance_km)} stroke="#dce3e7"/><text x="79" y={y(s.distance_km)+4} textAnchor="end" className="svg-small">{s.id} · {s.distance_km} {tr("km")}</text></g>)}
 {Array.from({length:9},(_,i)=>{const t=start+(end-start)*i/8;return <g key={i}><line x1={x(t)} x2={x(t)} y1="40" y2="430" stroke="#e8ecef"/><text x={x(t)} y="454" textAnchor="middle" className="svg-mono">{clock(t).slice(0,5)}</text></g>})}
 <g clipPath="url(#diagram-clip)">{trains.map(t=>{const original=state.baseline.filter(v=>v.train_id===t.id),actual=state.schedule.filter(v=>v.train_id===t.id),recommendation=(preview||state.schedule).filter(v=>v.train_id===t.id);const opacity=selected&&selected!==t.id?.22:1;return <g key={t.id} opacity={opacity} onClick={()=>onSelect(t.id)} className="trajectory" onMouseEnter={()=>setHover(`${t.id} · ${label(t.type)} · arrival ${clock(t.eta)} · +${minutes(t.delay_seconds)}`)} onMouseLeave={()=>setHover('')}><polyline points={path(original)} fill="none" stroke={trainColor(t)} strokeWidth="1.5" strokeDasharray="5 5" opacity=".35"/><polyline points={path(recommendation.filter(v=>v.end>state.time))} fill="none" stroke={selected===t.id?'#398e8b':trainColor(t)} strokeWidth={selected===t.id?3.5:2}/><polyline points={path(actual.filter(v=>v.start<=state.time).map(v=>v.end>state.time?{...v,end:state.time,to_km:t.distance_km}:v))} fill="none" stroke="#1c3345" strokeWidth="2.5"/><polyline points={path(recommendation)} fill="none" stroke="transparent" strokeWidth="12"/><circle cx={x(state.time)} cy={y(t.distance_km)} r="4" fill={trainColor(t)}/></g>})}
 {state.conflicts.map(c=>{const b=state.blocks.find(b=>b.id===c.location),s=state.stations.find(s=>s.id===c.location);return <g key={c.id}><circle cx={x(c.start_time)} cy={y(b?(b.start_km+b.end_km)/2:s?.distance_km||0)} r="9" fill="#fff4ef" stroke="#c55749"/><text x={x(c.start_time)} y={y(b?(b.start_km+b.end_km)/2:s?.distance_km||0)+4} textAnchor="middle" fill="#c55749" fontSize="12">!</text><title>{tr(c.description)}</title></g>})}
 <line x1={x(state.time)} x2={x(state.time)} y1="38" y2="430" stroke="#b9842d" strokeWidth="1.5" strokeDasharray="4 3"/></g><text x={Math.max(100,Math.min(1010,x(state.time)))} y="26" textAnchor="middle" fill="#a2762d" fontSize="11">{tr("NOW")}{clock(state.time).slice(0,5)}</text>
 </svg><div className="chart-caption">{tr(hover||'Select a trajectory to inspect its resource schedule. Horizontal segments indicate station dwell.')}</div></div>
}

export function TrainDrawer({train,state,onClose}:{train:Train;state:Snapshot;onClose:()=>void}){return <div className="drawer-backdrop" onClick={onClose}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="eyebrow">{tr("SERVICE INSPECTOR")}</span><h2><TrainFront size={22}/> {train.id}</h2></div><button aria-label={tr("Close train inspector")} onClick={onClose}><X size={18}/></button></div><Badge tone={train.upcoming_conflicts.length?'red':'green'}>{label(train.status)}</Badge><p>{label(train.type)} · {train.service_number}</p><dl>{Object.entries({[tr("Priority")]:train.priority,[tr("Origin")]:state.stations.find(s=>s.id===train.origin)?.name,[tr("Destination")]:state.stations.find(s=>s.id===train.destination)?.name,[tr("Current block")]:train.block_id||'Station / holding point',[tr("Route position")]:`${train.distance_km} km`,[tr("Current speed")]:`${train.speed_kmh} km/h`,[tr("Allowed speed")]:`${train.allowed_speed} km/h`,[tr("Projected delay")]:minutes(train.delay_seconds),[tr("Next station")]:train.next_station,[tr("Next station ETA")]:clock(train.next_station_eta),[tr("Final arrival")]:clock(train.eta),[tr("Energy proxy")]:`${train.energy_estimate} units (simulation)`}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{typeof v==='string'?tr(v):v}</dd></div>)}</dl><div className="callout"><span className="eyebrow">{tr("CURRENT RECOMMENDATION")}</span><p>{tr(train.recommendation)}</p></div><h3>{tr("Upcoming conflicts")}</h3>{train.upcoming_conflicts.length?train.upcoming_conflicts.map(c=><p className="conflict-note" key={c.id}>{tr(c.description)}</p>):<p className="muted">{tr("No predicted resource conflicts.")}</p>}</aside></div>}
