import {t as tr,useLanguage,LanguageSwitcher} from './i18n';
import {StrictMode,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,NavLink,Routes,Route,Navigate} from 'react-router-dom';
import {ChartNoAxesCombined,TriangleAlert,Layers,History as HistoryIcon,TrainFront,Pause,Play,LogOut,ChevronDown,Radio,ArrowRight,ShieldCheck} from 'lucide-react';
import type {PageProps} from './page-contract';
import {Dispatch} from '../../../movement_plan/Dispatch';
import {History} from '../../../history_reports/History';
import {YardBrain} from '../../../wagons_consists/YardBrain';
import type {Session,Snapshot} from './types';
import {clock,request} from './services';
import {useLive} from './hooks';
import {TrainDrawer} from './components';
import './style.css';
import './resource-style.css';

const navigation=[{path:'/dispatch',label:"Dispatch Plan",icon:ChartNoAxesCombined},{path:'/history',label:"History & Reports",icon:HistoryIcon},{path:'/yard',label:"Yard Brain",icon:Layers}];
function App(){
 useLanguage();
 const [session,setSession]=useState<Session|null>(()=>{try{return JSON.parse(sessionStorage.getItem('session')||'null')}catch{return null}}),[selected,setSelected]=useState<string|null>(null),[message,setMessage]=useState('');
 const {state,setState,connection,latency}=useLive(session);
 function notify(text:string){setMessage(text);setTimeout(()=>setMessage(''),7000)}
 async function act(path:string,body?:unknown){try{const result=await request<Snapshot>(path,session,'POST',body);if(result&&'trains' in result)setState(result);else setState(await request<Snapshot>('/api/state',session));return true}catch(e){notify(e instanceof Error?e.message:String(e));return false}}
 if(!session)return <Login onLogin={s=>{sessionStorage.setItem('session',JSON.stringify(s));setSession(s)}}/>;
 const props:PageProps|null=state?{state,session,select:setSelected,act,notify}:null;
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><TrainFront size={24}/></div><div><strong>{tr("JIBEK JOLY")}</strong><span>{tr("RAILWAY OPERATIONS")}</span></div></div><div className="workspace"><span className="eyebrow">{tr("CONTROL SECTION")}</span><strong>{tr("Arqa — Dala")}<ChevronDown size={13}/></strong><span>{tr("Sector 01 · 164 km")}</span></div><nav>{navigation.map(({path,label,icon:Icon},i)=><NavLink end={path==='/'} to={path} key={path} aria-label={tr(label)}><Icon size={18}/><span>{tr(label)}</span>{path==='/incidents'&&!!state?.incidents.filter(i=>i.status==='active').length&&<b>{state.incidents.filter(i=>i.status==='active').length}</b>}{i===0&&<small>01</small>}</NavLink>)}</nav><div className="sidebar-bottom"><div className="demo-label"><ShieldCheck size={16}/><div><strong>{tr("Synthetic operations")}</strong><span>{tr("Advisory simulation only")}</span></div></div><div className="user-row"><div className="avatar">{session.username[0].toUpperCase()}</div><div><strong>{session.username==='admin'?tr("Demo Administrator"):tr("Demo Dispatcher")}</strong><span>{tr(session.role)}</span></div><button aria-label={tr("Sign out")} onClick={()=>{sessionStorage.removeItem('session');setSession(null)}}><LogOut size={16}/></button></div></div></aside>
 <div className="app-content"><header className="topbar"><div className={`live-indicator ${connection==='LIVE'?'':'disconnected'}`}><i/>{tr(connection)}</div><span className="top-divider"/><div className="sim-clock"><span>{tr("SIMULATION TIME")}</span><strong>{state?clock(state.time):'--:--:--'}</strong></div><span className="time-zone">{tr("UTC+05")}</span><div className="top-right"><LanguageSwitcher/><span className="top-stat"><TrainFront size={15}/>{state?.trains.filter(t=>!['scheduled','completed'].includes(t.status)).length||0} {tr("active")}</span><span className="top-stat"><TriangleAlert size={15}/>{state?.incidents.filter(i=>i.status==='active').length||0} {tr("incidents")}</span><span className="top-qi">{tr("QI")}<strong>{state?.quality.value.toFixed(1)||'—'}</strong></span><button className="sim-button" disabled={!state} onClick={()=>void act(`/api/simulation/${state?.paused?'resume':'pause'}`).catch(()=>{})}>{state?.paused?<Play size={13}/>:<Pause size={13}/>} {state?.paused?tr("Resume"):tr("Pause")} <span>×{state?.speed||1}</span></button></div></header>
 {connection!=='LIVE'&&<div className="connection-banner"><Radio size={15}/> {connection==='CONNECTING'?tr("Connecting to the simulation…"):tr(`${connection}: showing the last received state. Automatic reconnect is active.`)}</div>}
 <main>{props?<Routes><Route path="/dispatch" element={<Dispatch {...props}/>}/><Route path="/history" element={<History {...props}/>}/><Route path="/yard" element={<YardBrain {...props}/>}/><Route path="*" element={<Navigate to="/dispatch" replace/>}/></Routes>:<div className="loading"><div className="spinner"/><h2>{tr("Loading railway state")}</h2><p>{tr("Connecting to the synthetic corridor.")}</p><button onClick={()=>{sessionStorage.removeItem('session');setSession(null)}}>{tr("Return to sign in")}</button></div>}</main><footer><span><i className="dot teal"/> {tr("Decision support · synthetic dataset · seed 42")}</span><span>{tr("WebSocket 1 Hz · UI processing")}{latency} {tr("ms · v1.0")}</span></footer></div>
 {selected&&state?.trains.find(t=>t.id===selected)&&<TrainDrawer state={state} train={state.trains.find(t=>t.id===selected)!} onClose={()=>setSelected(null)}/>} {message&&<div role="status" className="toast" onClick={()=>setMessage('')}>{tr(message)}</div>}</div>
}
function Login({onLogin}:{onLogin:(session:Session)=>void}){const [username,setUsername]=useState('dispatcher'),[password,setPassword]=useState('dispatch-demo'),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <div className="login"><LanguageSwitcher/><div className="login-brand"><TrainFront size={30}/><strong>{tr("JIBEK JOLY")}</strong><span>{tr("Railway operations · synthetic demonstration")}</span></div><form onSubmit={e=>{e.preventDefault();setBusy(true);request<Session>('/api/auth/login',null,'POST',{username,password}).then(onLogin).catch(e=>setError(String(e))).finally(()=>setBusy(false))}}><div className="eyebrow">{tr("LOCAL DEMO ACCESS")}</div><h1>{tr("Enter the control room")}</h1><p>{tr("Arqa — Dala synthetic railway corridor.")}</p><label>{tr("Account")}<select value={username} onChange={e=>{setUsername(e.target.value);setPassword(e.target.value==='admin'?'admin-demo':'dispatch-demo')}}><option value="dispatcher">{tr("Dispatcher")}</option><option value="admin">{tr("Administrator")}</option></select></label><label>{tr("Password")}<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label>{error&&<div className="error">{error}</div>}<button className="primary full" disabled={busy}>{busy?tr("Connecting…"):tr("Open operations")}<ArrowRight size={16}/></button><div className="login-note"><ShieldCheck size={17}/><span>{tr("Decision-support prototype. All traffic is fictional; recommendations apply to the simulator.")}</span></div></form></div>}
createRoot(document.getElementById('root')!).render(<StrictMode><BrowserRouter><App/></BrowserRouter></StrictMode>);
