import {useEffect,useState} from 'react';
import {ArrowRight,Check,Layers,RefreshCw} from 'lucide-react';
import type {PageProps} from '../shared_required_only/frontend/src/page-contract';
import {PageTitle} from '../shared_required_only/frontend/src/PageTitle';
import {Panel,Badge} from '../shared_required_only/frontend/src/components';
import {request,clock,label} from '../shared_required_only/frontend/src/services';
import {t,useLanguage} from '../shared_required_only/frontend/src/i18n';
import type {YardState,YardTrain,YardData} from './resource-types';

function useResource<S>(module:string,{session,notify}:PageProps){
 const [value,setValue]=useState<S|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){try{setValue(await request<S>(`/api/resources/${module}`,session));setError('')}catch(e){setError(String(e))}}
 useEffect(()=>{void load()},[module,session]);
 async function solve(train_id?:string){setBusy(true);setError('');try{setValue(await request<S>(`/api/resources/${module}/optimize`,session,'POST',{train_id:train_id||'F103',runtime_seconds:2}))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function apply(plan_id:string,option_id?:string){setBusy(true);try{setValue(await request<S>(`/api/resources/${module}/apply`,session,'POST',{plan_id,option_id}));notify(t('Resource plan applied to the simulator'))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return {value,busy,error,solve,apply,load};
}

function Provenance(){return <div className="resource-provenance"><Badge tone="amber">SIMULATED / DERIVED</Badge><span>{t('Synthetic resource scenario · seed 42 · mathematical optimization')}</span></div>}

function CalculateButton({busy,run,caption='Optimize resources'}:{busy:boolean;run:()=>void;caption?:string}){return <button className="primary" disabled={busy} onClick={run}>{busy?<RefreshCw className="rotating" size={14}/>:<Layers size={14}/>} {t(busy?'Solving resource constraints…':caption)}</button>}

function CompareMetric({title,before,after,unit,lower=true}:{title:string;before:number;after?:number;unit:string;lower?:boolean}){const improved=after!==undefined&&(lower?after<=before:after>=before);return <div className="compare-metric"><span>{t(title)}</span><div><strong className={after===undefined?'':'before-value'}>{before.toFixed(1)}</strong>{after!==undefined&&<><ArrowRight size={16}/><strong className={improved?'text-teal':'text-amber'}>{after.toFixed(1)}</strong></>}<small>{t(unit)}</small></div><p>{t(after===undefined?'Baseline measured from the current plan':'Before → after · derived from resource assignments')}</p></div>}

export function YardBrain(props:PageProps){
 useLanguage();
 const {value,busy,error,solve,apply}=useResource<YardState>('yard',props);
 const [mode,setMode]=useState<'before'|'after'>('after'),[selected,setSelected]=useState<string|null>(null),[frame,setFrame]=useState(6000);
 const result=value?.result,plan=(mode==='after'&&result?result.after:value?.baseline)||[];
 const metrics=value?.baseline_metrics;
 const train=plan.find(p=>p.id===selected)||plan[0];
 return <><PageTitle eyebrow={t('RESOURCE INTELLIGENCE / WAGONS')} title={t('Yard Brain')} description={t('Group wagons, reserve formation tracks and sequence shunting locomotives in one resource plan.')} action={<CalculateButton busy={busy} run={()=>void solve()} caption="Optimize wagon formation"/>}/><Provenance/>{error&&<div className="error" role="alert">{t(error)}</div>}
 {!value||!metrics?<div className="empty">{t('Loading resource scenario…')}</div>:<>
 <div className="resource-metrics"><CompareMetric title="Formed trains" before={metrics.train_count} after={result?.after_metrics.train_count} unit="trains"/><CompareMetric title="Wagon waiting" before={metrics.wagon_hours} after={result?.after_metrics.wagon_hours} unit="wagon-hours"/><CompareMetric title="Late wagon time" before={metrics.late_wagon_minutes} after={result?.after_metrics.late_wagon_minutes} unit="min"/><CompareMetric title="Mean train fill" before={metrics.mean_fill_percent} after={result?.after_metrics.mean_fill_percent} unit="%" lower={false}/></div>
 <div className="resource-layout"><div><Panel title={t('Aksai formation yard')} subtitle={t('Track reservations include assembly and departure clearance')} action={<div className="tabs"><button className={mode==='before'?'active':''} onClick={()=>setMode('before')}>{t('Before optimization')}</button><button className={mode==='after'?'active':''} disabled={!result} onClick={()=>setMode('after')}>{t('After optimization')}</button></div>}><YardSchematic data={value.data} plan={plan} frame={frame} selected={train?.id} select={setSelected}/><div className="yard-scrubber"><span>{t('Projected yard state')}</span><input type="range" aria-label={t('Yard timeline')} min={value.data.reference_time} max={Math.max(value.data.reference_time+7200,...plan.map(p=>p.departure))} value={frame} onChange={e=>setFrame(Number(e.target.value))}/><strong className="mono">{clock(frame)}</strong></div></Panel>
 <Panel title={t('Formation and departure sequence')} subtitle={`${value.data.wagons.length} ${t('wagons')} · ${plan.length} ${t('trains')}`}><div className="table-wrap"><table><thead><tr>{['Consist','Destination','Wagons','Track / shunter','Formation','Departure','Length / mass'].map(k=><th key={k}>{t(k)}</th>)}</tr></thead><tbody>{plan.map(p=><tr key={p.id} onClick={()=>setSelected(p.id)} className={train?.id===p.id?'row-selected':''}><td className="mono">{p.id}</td><td>{p.destination}</td><td>{p.wagon_ids.length}</td><td className="mono">{p.track_id} / {p.shunter_id}</td><td className="mono">{clock(p.formation_start).slice(0,5)}–{clock(p.formation_end).slice(0,5)}</td><td className="mono">{clock(p.departure).slice(0,5)}</td><td>{p.length_m} {t('m')} / {p.mass_t} {t('t')}</td></tr>)}</tbody></table></div></Panel></div>
 <div><Panel title={t('Consist inspector')} subtitle={train?.id||t('Select a formed train')}>{train&&<div className="padded"><div className="inspector-service"><strong>{train.id}</strong><Badge>{train.destination}</Badge></div><dl>{[[t('Wagons'),train.wagon_ids.length],[t('Length limit'),`${train.length_m} / ${train.length_limit_m} ${t('m')}`],[t('Mass limit'),`${train.mass_t} / ${value.data.max_train_mass_t} ${t('t')}`],[t('Shunting locomotive'),train.shunter_id],[t('Departure'),clock(train.departure)]].map(([k,v])=><div key={String(k)}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="wagon-list">{train.wagon_ids.map(id=>{const w=value.data.wagons.find(w=>w.id===id)!;return <span key={id} title={`${label(w.cargo)} · ${w.mass_t} ${t('t')} · ${t('Deadline')} ${clock(w.deadline)}`}>{id}</span>})}</div><p className="muted resource-small">{t('All wagons share a destination. Hover an ID to inspect cargo, mass and deadline.')}</p></div>}</Panel>
 <Panel title={t('Algorithm and measurable effect')} subtitle="CP-SAT / feasible batching"><div className="padded resource-explanation"><p>{t('Joint bin packing and interval scheduling: wagon destination, arrival and deadline; train length and mass; track capacity and shunting availability.')}</p>{result?<><div className="effect-line"><strong>{result.slots_freed}</strong><span>{t('Departure slots freed')}</span></div><div className="effect-line"><strong>{result.wagon_hours_saved?.toFixed(2)}</strong><span>{t('Wagon-hours saved')}</span></div><p className="mono">{result.engine} · {result.calculation_time_ms.toFixed(0)} {t('ms')}</p><div className="verified"><Check size={14}/>{t('120 wagons assigned once · zero resource overlaps')}</div><button className="primary full" disabled={busy||value.applied?.plan_id===result.plan_id} onClick={()=>void apply(result.plan_id)}>{t(value.applied?.plan_id===result.plan_id?'Applied to resource simulator':'Apply resource plan')}</button></>:<p className="muted">{t('Run optimization to compare a feasible plan against the baseline.')}</p>}</div></Panel></div></div>
 <Panel title={t('Wagon inventory')} subtitle={t('Synthetic arrivals, freight priorities and dispatch deadlines')}><div className="inventory-grid">{value.data.wagons.map(w=><button key={w.id} className={`inventory-wagon cargo-${w.cargo}`} onClick={()=>{const p=plan.find(p=>p.wagon_ids.includes(w.id));if(p)setSelected(p.id)}} title={`${w.destination} · ${label(w.cargo)} · ${clock(w.arrival_time)} → ${clock(w.deadline)}`}><strong>{w.id}</strong><span>{w.destination} · {w.mass_t} {t('t')}</span></button>)}</div></Panel>
 </>}</>
}

function YardSchematic({data,plan,frame,selected,select}:{data:YardData;plan:YardTrain[];frame:number;selected?:string;select:(id:string)=>void}){
 return <svg className="yard-svg" viewBox="0 0 980 370" role="img" aria-label={t('Yard tracks and wagon formation')}><text x="30" y="30" className="svg-eyebrow">S7 / {t('Aksai Yard')}</text><path d="M 30 180 H 120 M 95 180 L 160 75 M 95 180 L 160 145 M 95 180 L 160 215 M 95 180 L 160 285" fill="none" stroke="#b3c1ca" strokeWidth="2"/>
 {data.tracks.map((track,i)=>{const y=75+i*70,active=plan.find(p=>p.track_id===track.id&&p.formation_start<=frame&&frame<p.departure),ready=frame>=track.available_time;return <g key={track.id}><line x1="160" x2="910" y1={y} y2={y} stroke={active?'#478f8a':ready?'#b4c3cc':'#ba8c42'} strokeWidth="4"/><text x="20" y={y+4} className="svg-mono">{track.id}</text><text x="940" y={y+4} textAnchor="end" className="svg-small">{track.length_m} {t('m')}</text>{active?<g tabIndex={0} role="button" aria-label={active.id} onClick={()=>select(active.id)} onKeyDown={e=>{if(e.key==='Enter')select(active.id)}} className="yard-consist"><text x="170" y={y-31} className="svg-mono">{active.id} → {active.destination} / {active.shunter_id}</text>{active.wagon_ids.map((id,j)=><g key={id}><rect x={170+j*23} y={y-22} width="21" height="17" rx="2" fill={active.id===selected?'#245970':'#559b93'}/><circle cx={175+j*23} cy={y-3} r="2" fill="#304e60"/><circle cx={185+j*23} cy={y-3} r="2" fill="#304e60"/></g>)}<text x="920" y={y-18} textAnchor="end" className="svg-small">{clock(active.departure).slice(0,5)}</text></g>:<text x="180" y={y-13} className="svg-small">{t(ready?'Track available':'Existing occupation until')} {!ready&&clock(track.available_time).slice(0,5)}</text>}</g>})}<text x="30" y="335" className="svg-small">{t('Formation trains occupy a track until departure; shunters are reserved only during assembly.')}</text></svg>
}
