import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {nodes,position,incidentFor,trainDefs} from './corridor-engine.js';
export function corridorScene(host,{lang=0,dark=true,compact=false,onTrain=()=>{},onBlock=()=>{},onStation=()=>{}}={}){
 const root=document.createElement('div');root.className='corridor-canvas';const overlay=document.createElement('div');overlay.className='world-labels';host.append(root,overlay);
 let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false})}catch(e){root.innerHTML=`<div class="webgl-fallback">${lang?'3D қолжетімсіз. Төмендегі тірі сызба мен басқару панелі жұмыс істейді.':'3D недоступно. Живая схема и панель управления ниже продолжают работать.'}</div>`;return{update(){},dispose(){host.replaceChildren()},view(){},follow(){},select(){}}}
 const scene=new THREE.Scene();scene.background=new THREE.Color(dark?'#12242b':'#dfebee');scene.fog=new THREE.Fog(scene.background,400,800);
 const camera=new THREE.PerspectiveCamera(36,1,.1,900);const overview=()=>{const f=Math.max(1,1.45/(host.clientWidth/Math.max(1,host.clientHeight)));camera.position.set(22*f,138*f,160*f);controls.target.set(0,0,0)};
 renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;root.append(renderer.domElement);renderer.domElement.setAttribute('aria-label',lang?'Бүкіл дәліздің интерактивті 3D моделі':'Интерактивная 3D-модель всего коридора');
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=25;controls.maxDistance=480;controls.maxPolarAngle=Math.PI/2.18;overview();
 scene.add(new THREE.HemisphereLight(0xd7f7ff,0x315455,2.6));const sun=new THREE.DirectionalLight(0xfff4df,2.4);sun.position.set(-30,120,50);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-110,right:110,top:70,bottom:-70});scene.add(sun);
 const mats=new Map();function mat(c){if(!mats.has(c))mats.set(c,new THREE.MeshStandardMaterial({color:c,roughness:.72,metalness:.12}));return mats.get(c)}
 const box=(w,h,d,c,x,y,z,parent=scene)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o};
 box(202,1,67,dark?'#263c43':'#c4d7d9',1,-1,0);const grid=new THREE.GridHelper(200,40,dark?0x38545c:0xa6c0c6,dark?0x2b444b:0xb5ccd1);grid.position.y=-.46;scene.add(grid);
 const rails=[],reserveRails=[],hazards=[],blockLabels=[];
 const makeLink=(a,b,offset,c,width=.13)=>{const dx=b.x-a.x,dz=b.z-a.z,len=Math.hypot(dx,dz),o=box(len,.15,width,c,(a.x+b.x)/2,.13,(a.z+b.z)/2+offset);o.rotation.y=-Math.atan2(dz,dx);return o;};
 for(let i=0;i<8;i++){const a=nodes[i],b=nodes[i+1],dx=b.x-a.x,dz=b.z-a.z,len=Math.hypot(dx,dz);makeLink(a,b,0,dark?'#38484c':'#94a6a9',2.4);rails.push([makeLink(a,b,-.65,'#a6c6ce'),makeLink(a,b,.65,'#a6c6ce')]);reserveRails.push([makeLink(a,b,-4-.65,'#3f6a70'),makeLink(a,b,-4+.65,'#3f6a70')]);for(let p=0;p<1;p+=1.3/len){const sl=box(.23,.16,2.05,dark?'#657170':'#727c7c',a.x+dx*p,.06,a.z+dz*p);sl.rotation.y=-Math.atan2(dz,dx);}const g=new THREE.Group();g.position.set((a.x+b.x)/2,0,(a.z+b.z)/2+2.5);scene.add(g);box(.18,3,.18,'#9ca8a8',0,1.5,0,g);const signal=new THREE.Mesh(new THREE.SphereGeometry(.5,12,8),mat('#37d3b4'));signal.position.y=3.2;g.add(signal);hazards.push(signal);
 const btt=document.createElement('button');btt.className='block-label';btt.setAttribute('aria-label',`${a.name} — ${b.name}`);btt.onclick=()=>onBlock(i);overlay.appendChild(btt);blockLabels.push({el:btt,pos:new THREE.Vector3((a.x+b.x)/2,4,(a.z+b.z)/2-6)});}
 const stationLabels=nodes.map((n,i)=>{const major=[0,3,8].includes(i);for(const off of [3,6]){box(11,.28,1,dark?'#70818a':'#e0e7e8',n.x,.15,n.z+off);box(12,.08,.1,'#e7c263',n.x,.35,n.z+off-.45);}for(const off of [-.8,.8])box(15,.12,.12,'#b4c7ce',n.x,.2,n.z+4.5+off);box(major?10:6,major?4:2.6,3.2,major?(dark?'#426b76':'#dae9ed'):(dark?'#42616a':'#c1d5dc'),n.x,major?1.8:1.1,n.z+12);box(major?11:7,.3,4,'#668b94',n.x,major?3.95:2.55,n.z+12);for(let x=-2;x<=2;x+=2)box(1.3,1.4,.08,'#8ac5d2',n.x+x,1.4,n.z+10.36);const e=document.createElement('button');e.className='world-station'+(major?' major':'');e.textContent=n.name;e.onclick=()=>onStation(i);overlay.appendChild(e);return {el:e,pos:new THREE.Vector3(n.x,major?6:4,n.z+13)};});
 const pickables=[];const trains=trainDefs.map((t,i)=>{const g=new THREE.Group();scene.add(g);for(let j=0;j<3;j++){box(2.7,1.05,1.2,t.color,-j*3,1.05,0,g);box(2.55,.25,1.05,'#d7e9ec',-j*3,1.7,0,g);box(2.6,.35,1.1,'#233944',-j*3,.4,0,g);for(const z of [-.61,.61])for(const x of [-.8,.1,1])box(.6,.4,.025,'#153c49',-j*3+x,1.24,z,g);for(const x of [-.8,.8]){const wheel=new THREE.Mesh(new THREE.CylinderGeometry(.23,.23,1.4,8),mat('#142831'));wheel.rotation.x=Math.PI/2;wheel.position.set(-j*3+x,.25,0);g.add(wheel);}}box(.05,.65,.95,'#a0e8ee',1.38,1.25,0,g);g.traverse(o=>{if(o.isMesh){o.userData.train=i;pickables.push(o)}});const ring=new THREE.Mesh(new THREE.RingGeometry(2.1,2.35,32),new THREE.MeshBasicMaterial({color:t.color,side:THREE.DoubleSide,transparent:true,opacity:.9}));ring.rotation.x=-Math.PI/2;ring.position.y=.08;g.add(ring);ring.visible=false;const el=document.createElement('button');el.className='world-train';el.style.setProperty('--train',t.color);el.style.marginTop=(-(i%3)*18)+'px';el.onclick=()=>onTrain(t.id);overlay.appendChild(el);return{g,ring,el,definition:t};});
 let selected=null,followId=null,world=null,ended=false,raf;const vector=new THREE.Vector3();let vw=1,vh=1;
 function project(el,p){vector.copy(p).project(camera);const x=(vector.x+1)/2*vw,y=(1-vector.y)/2*vh;el.style.left=x+'px';el.style.top=y+'px';el.hidden=vector.z>1||vector.z<-1||x<-50||x>vw+50||y<-40||y>vh+40;}
 function draw(){if(ended)return;if(followId&&world){const tr=trains.find(t=>t.definition.id===followId);if(tr){const desired=new THREE.Vector3(tr.g.position.x+12,28,tr.g.position.z+34);camera.position.lerp(desired,.045);controls.target.lerp(tr.g.position,.06);}}controls.update();renderer.render(scene,camera);stationLabels.forEach(({el,pos})=>project(el,pos));blockLabels.forEach(({el,pos})=>project(el,pos));trains.forEach((t,i)=>project(t.el,new THREE.Vector3(t.g.position.x-2,5+(i%2)*2,t.g.position.z)));raf=requestAnimationFrame(draw);}
 const resize=()=>{vw=host.clientWidth;vh=host.clientHeight;if(!vw||!vh)return;camera.aspect=vw/vh;camera.updateProjectionMatrix();renderer.setSize(vw,vh);};const observer=new ResizeObserver(resize);observer.observe(host);resize();draw();
 controls.addEventListener('start',()=>{followId=null});let start=null;renderer.domElement.addEventListener('pointerdown',e=>start=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!start||Math.hypot(e.clientX-start[0],e.clientY-start[1])>6)return;const r=renderer.domElement.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hits=ray.intersectObjects(pickables);if(hits[0])onTrain(trainDefs[hits[0].object.userData.train].id)});
 return {update(w){world=w;for(let i=0;i<8;i++){const inc=incidentFor(w,i),busy=w.blocks[i].main;const color=inc?.type==='closure'?'#ff6f7d':inc?'#efb555':busy?'#72acff':'#68b2b3';rails[i].forEach(r=>r.material=mat(color));hazards[i].material=mat(color);reserveRails[i].forEach(r=>r.material=mat(w.blocks[i].reserveOpen?'#34d9b6':'#416169'));const e=blockLabels[i].el;e.classList.toggle('danger',inc?.type==='closure');e.classList.toggle('slow',inc?.type==='slow');e.classList.toggle('reserve',w.blocks[i].reserveOpen);e.textContent=inc?(inc.type==='slow'?'40 '+(lang?'км/сағ':'км/ч'):(lang?'ЖАБЫҚ':'ЗАКРЫТ')):w.blocks[i].reserveOpen?(lang?'РЕЗЕРВ':'РЕЗЕРВ'):'';e.style.display=inc||w.blocks[i].reserveOpen?'':'none';}
 w.trains.forEach((t,i)=>{const pos=position(t),item=trains[i];item.g.position.set(pos.x,0,pos.z);item.g.rotation.y=-pos.angle;item.el.innerHTML=`<b>${t.id}</b><span class="${t.delay<=5?'good':t.delay<=15?'warn':'bad'}">${t.finished!==null?'✓ ':''}+${Math.round(t.delay)}′</span>`;item.el.classList.toggle('selected',selected===t.id);item.ring.visible=selected===t.id;item.el.classList.toggle('stopped',['queue','blocked','held'].includes(t.state));});},
 select(id){selected=id;if(world)this.update(world)},follow(id){selected=id;followId=id},view(v){followId=null;if(v==='top'){camera.position.set(0,Math.max(185,320/camera.aspect),.01);controls.target.set(0,0,0)}else if(v==='side'){camera.position.set(-110,65,110);controls.target.set(0,0,0)}else overview();controls.update()},dispose(){ended=true;cancelAnimationFrame(raf);observer.disconnect();controls.dispose();scene.traverse(o=>o.geometry?.dispose());mats.forEach(m=>m.dispose());renderer.dispose();host.replaceChildren()}};
}
