import {nodes,signalState,incidentFor} from './corridor-engine.js';
import {ecoText} from './eco-ui.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// A view of the supplied world only: no second simulator or station dataset.
export function dispatcherScheme(w,selected,lang=0,readOnly=false){
 const text=k=>ecoText(k,lang),x=i=>90+i*145;
 return `<div class="dispatcher-scroll"><svg class="dispatcher-scheme" viewBox="0 0 1340 400" role="group" aria-label="${text('map2d')}"><text x="30" y="30" class="scheme-note">${text('schemeNote')}</text>${w.blocks.map(b=>{
  const e=incidentFor(w,b.i),color=e?.type==='closure'?'var(--red)':e?'var(--amber)':b.main?'var(--blue)':'var(--muted)';
  return `<g role="button" tabindex="0" data-act="block" data-id="${b.i}" aria-label="${esc(nodes[b.i].name+' — '+nodes[b.i+1].name)}"><title>${esc(nodes[b.i].name+' — '+nodes[b.i+1].name)}</title><rect x="${x(b.i)}" y="130" width="145" height="100" fill="transparent"/><path d="M${x(b.i)} 164H${x(b.i+1)}" stroke="${color}" stroke-width="5"/><path d="M${x(b.i)} 196H${x(b.i+1)}" stroke="${b.reserveOpen?(b.reserve?'var(--blue)':'var(--accent)'):'var(--line)'}" stroke-width="4" ${b.reserveOpen?'':'stroke-dasharray="6 5"'}/>${[1,-1].map(dir=>{const s=signalState(w,b.i,dir),sx=x(b.i)+(dir===1?115:30),y=dir===1?146:214;return `<g ${readOnly?'':`role="button" tabindex="0" data-act="signal" data-id="${b.i}" data-dir="${dir}"`} aria-label="${esc(text('schemeSignal')+' '+nodes[b.i].name+' — '+nodes[b.i+1].name+' '+(dir===1?'→':'←')+' '+s.aspect)}"><title>${esc(s.id+' · '+s.aspect)}</title><circle cx="${sx}" cy="${y}" r="10" fill="var(--panel)"/><circle cx="${sx}" cy="${y}" r="5" fill="${s.aspect==='green'?'var(--accent)':'var(--red)'}"/></g>`}).join('')}</g>`;
 }).join('')}${nodes.map((s,i)=>`<g role="button" tabindex="0" data-act="station" data-id="${i}" data-station-id="${s.id}" aria-label="${esc(s.name)}"><rect x="${x(i)-8}" y="152" width="16" height="56" rx="4" fill="var(--panel2)" stroke="var(--text)"/><text x="${x(i)}" y="260" text-anchor="middle" class="scheme-station">${esc(s.name)}</text></g>`).join('')}${w.trains.map((t,i)=>{const px=x(t.segment===null?t.node:t.segment+t.p),y=t.dir===1?55+(i%3)*30:290+(i%3)*32;return `<g role="button" tabindex="0" data-act="train" data-id="${t.id}" aria-label="${esc(t.id)}" class="scheme-train ${selected===t.id?'selected':''}"><line x1="${px}" x2="${px}" y1="${y+12}" y2="${t.lane==='reserve'?196:164}" stroke="${t.color}" stroke-dasharray="3 4"/><rect x="${px-65}" y="${y}" width="130" height="25" rx="5" fill="var(--panel2)" stroke="${t.color}"/><text x="${px}" y="${y+17}" text-anchor="middle">${esc(t.id)} ${t.dir===1?'→':'←'} +${t.delay.toFixed(1)}′</text></g>`}).join('')}</svg></div><div class="world-key"><span><i style="background:var(--blue)"></i>${text('schemeOccupied')}</span><span><i style="background:var(--accent)"></i>${text('schemeReserve')}</span><span><i style="background:var(--red)"></i>${text('schemeClosed')}</span><span>${text('schemeActions')}</span></div>`;
}
