// Compact, immutable trip frames. No nested histories inside each frame.
const states=['ready','running','queue','blocked','held','done'];
const r=n=>Math.round((Number(n)||0)*10000)/10000;
export function advice(w,t){const block=t.segment??(t.dir===1?t.node:t.node-1);const inc=w.incidents.filter(e=>e.block===block&&e.until>w.time).sort((a,b)=>(b.type==='closure')-(a.type==='closure'))[0];const lane=t.segment===null?(w.blocks[block]?.reserveOpen?'reserve':'main'):t.lane;let limit=Math.min(60/(t.type===0?1:t.type===1?1.13:1.38),lane==='reserve'?48:inc?.type==='slow'?40:60);let reason='cruise';if(t.finished!==null){limit=0;reason='arrived';}else if(t.hold&&t.segment===null){limit=0;reason='hold';}else if(inc?.type==='closure'&&lane==='main'){limit=0;reason='signal';}else if(t.segment===null&&['queue','held'].includes(t.state)){limit=0;reason='queue';}else if(lane==='reserve')reason='reserve';else if(inc?.type==='slow')reason='restriction';const lengths=[9,11,8,14,12,10,9,7];const remaining=block>=0&&block<8?lengths[block]*(t.segment===null?1:t.dir===1?1-t.p:t.p):0;const brake=Math.sqrt(Math.max(0,2*.35*remaining*1000))*3.6;let speed=Math.min(limit,brake);if(speed<limit-1&&limit>0)reason='brake';else if(limit>0&&(t.actualSpeed||0)<limit-5)reason='accelerate';return {speed:r(speed),limit:r(limit),actual:t.state==='running'?r(t.actualSpeed):0,reason,remaining:r(remaining)};}
export function recordFrame(w,force=false){if(w.recordJourney===false)return;if(!w.timeline)w.timeline=[];const prev=w.timeline.at(-1);if(!force&&prev&&w.time-prev.time<.499)return;const frame={time:r(w.time),trains:w.trains.map(t=>{const a=advice(w,t);return [t.node,t.segment,r(t.p),states.indexOf(t.state),t.lane==='reserve'?1:0,r(t.delay),a.actual,a.speed,a.limit,a.reason,t.finished===null?null:r(t.finished),t.hold?1:0,r(t.work),r(t.wait),r(t.energy)];}),blocks:w.blocks.map(b=>[b.main,b.reserve,b.reserveOpen?1:0,r(b.freeAt),r(b.reserveFreeAt),b.preferred]),incidents:w.incidents.map(e=>[e.index,e.block,e.time,r(e.until),e.type,e.repair?1:0,e.managed?1:0]),actions:w.actions,done:w.done};if(prev&&Math.abs(prev.time-frame.time)<.0001)w.timeline[w.timeline.length-1]=frame;else w.timeline.push(frame);}
export function frameWorld(base,f){return {...base,time:f.time,timeline:[],history:[],log:[],trains:base.trains.map((t,i)=>{const a=f.trains[i];return {...t,node:a[0],segment:a[1],p:a[2],state:states[a[3]]||'ready',lane:a[4]?'reserve':'main',delay:a[5],actualSpeed:a[6],recommendedSpeed:a[7],speedLimit:a[8],speedReason:a[9],finished:a[10],hold:!!a[11],work:a[12],wait:a[13],energy:a[14]};}),blocks:base.blocks.map((b,i)=>{const a=f.blocks[i];return {...b,main:a[0],reserve:a[1],reserveOpen:!!a[2],freeAt:a[3],reserveFreeAt:a[4],preferred:a[5]};}),incidents:f.incidents.map(a=>({...base.incidents.find(e=>e.index===a[0]),index:a[0],block:a[1],time:a[2],until:a[3],type:a[4],repair:!!a[5],managed:!!a[6]})),actions:f.actions,done:f.done};}
export function tripSamples(w){return (w.timeline||[]).map(f=>({time:f.time,world:frameWorld(w,f)}));}
export function speedChanges(w,id){const i=w.trains.findIndex(t=>t.id===id),rows=[];for(const f of w.timeline||[]){const a=f.trains[i],prev=rows.at(-1);if(!prev||Math.abs(prev.actual-a[6])>1||prev.reason!==a[9])rows.push({time:f.time,actual:a[6],recommended:a[7],limit:a[8],reason:a[9]});}return rows;}
export const reasonText={cruise:['Движение по участку','Учаскеде қозғалыс'],arrived:['Прибытие','Келу'],hold:['Удержание диспетчером','Диспетчер ұстауы'],signal:['Закрытый сигнал','Жабық сигнал'],queue:['Ожидание свободного пути','Бос жолды күту'],reserve:['Резервный путь','Резервтік жол'],restriction:['Ограничение скорости','Жылдамдық шектеуі'],brake:['Торможение перед станцией','Станция алдында тежеу'],accelerate:['Набор скорости','Жылдамдық алу']};
