import {advice} from './journey.js';
import {step,action,assertWorld,metrics,incidentFor,durations,targetBlock} from './corridor-engine.js';
import {quality,defaultConfig} from './quality.js';
export const policies=[
{id:'base',name:['Ожидание по очереди','Кезекпен күту'],order:'fifo',repair:false,reserve:false},
{id:'repair',name:['Ремонт + пассажирский приоритет','Жөндеу + жолаушы басымдығы'],order:'passenger',repair:true,reserve:false},
{id:'reserve',name:['Резерв + пассажирский приоритет','Резерв + жолаушы басымдығы'],order:'passenger',repair:false,reserve:true},
{id:'combined',name:['Ремонт, резерв, пассажиры','Жөндеу, резерв, жолаушылар'],order:'passenger',repair:true,reserve:true},
{id:'delay',name:['Сначала опаздывающие','Алдымен кешіккендер'],order:'delay',repair:true,reserve:true},
{id:'freight',name:['Сначала грузовые','Алдымен жүк пойыздары'],order:'freight',repair:true,reserve:true}
];
export function applyPolicy(w,p){w.policy=p.order;for(const e of w.incidents.filter(e=>e.until>w.time)){if(p.repair&&!e.repair){e.until=Math.min(e.until,w.time+6);e.repair=true;e.managed=true;}if(p.reserve)action(w,'reserve',null,e.block);}w.planId=p.id;}
export function forecast(input,config=defaultConfig){const started=performance.now(),start=input.time;const candidates=policies.map(p=>{const w=structuredClone({...input,timeline:[]});w.recordJourney=false;w.config=config;w.events=false;w.auto=false;w.history=[];w.log=[];applyPolicy(w,p);const traces=w.trains.map(t=>({id:t.id,color:t.color,points:[]}));let checks=0;while(!w.done&&w.time<start+240){for(let i=0;i<w.trains.length;i++){const t=w.trains[i];traces[i].points.push([w.time,t.segment===null?t.node:t.segment+t.p,t.lane]);}step(w,.5);assertWorld(w);checks++;}for(let i=0;i<w.trains.length;i++){const t=w.trains[i];traces[i].points.push([w.time,t.segment===null?t.node:t.segment+t.p,t.lane]);}const m=metrics(w),q=quality(w,config);return {policy:p,metrics:m,quality:q,traces,arrivals:w.trains.map(t=>({id:t.id,time:t.finished,delay:t.delay})),valid:w.done,checks,score:m.weighted+(w.trains.length-m.finished)*10000+q.energy*.05};});const valid=candidates.filter(c=>c.valid).sort((a,b)=>a.score-b.score);return {start,ms:performance.now()-started,candidates,best:valid[0]?.policy.id||'base',valid:valid.length>0};}
export function stressWorld(input,count){const w=structuredClone(input);w.events=false;for(let i=0;i<count;i++)w.incidents.push({index:i%4,block:i%8,time:w.time,until:w.time+10+i*2,type:i%3?'closure':'slow',repair:false,managed:false,synthetic:true});return w;}
export function atoProfile(w,id){const t=w.trains.find(t=>t.id===id),a=advice(w,t),block=Math.max(0,Math.min(7,targetBlock(t))),vmax=a.limit,points=[],distance=Math.max(.01,a.remaining);for(let i=0;i<=50;i++){const x=distance*i/50,brake=Math.sqrt(Math.max(0,2*.35*(distance-x)*1000))*3.6,accel=Math.sqrt(Math.max(0,2*.3*x*1000+a.actual*a.actual/12.96))*3.6;points.push({km:x,limit:vmax,speed:Math.min(vmax,accel,brake)*(i>32?.92:1)});}const time=points.slice(1).reduce((s,p,i)=>s+(p.km-points[i].km)/Math.max(1,(p.speed+points[i].speed)/2)*60,0),base=points.reduce((s,p)=>s+p.limit*p.limit,0),eco=points.reduce((s,p)=>s+p.speed*p.speed,0);return {block,limit:vmax,points,minutes:vmax?time:null,saving:base?Math.round((1-eco/base)*100):0,reason:a.reason==='arrived'?'done':a.reason==='hold'?'hold':vmax===0?'stop':'drive',target:w.time+(vmax?time:0),distance};}
