import {PDFDocument,rgb} from 'pdf-lib';
import fontkit from '@pdf-lib/fontkit';
import {nodes} from './corridor-engine.js';
import {speedChanges,reasonText} from './journey.js';
export async function pdfReport({world,quality,plan,lang=0,trip=null,selected='TAL-021',source=''}){
 const pdf=await PDFDocument.create();pdf.registerFontkit(fontkit);const font=await pdf.embedFont(await (await fetch('/vendor/report-font.ttf')).arrayBuffer(),{subset:true});let page,y;const kk=!!lang,t=(a,b)=>kk?b:a,newPage=()=>{page=pdf.addPage([595,842]);y=790;};newPage();const add=(s,size=11,color=rgb(.13,.2,.25))=>{if(y<55)newPage();page.drawText(String(s),{x:42,y,size,font,color});y-=size+12;};const clock=m=>`${String(8+Math.floor(m/60)).padStart(2,'0')}:${String(Math.floor(m%60)).padStart(2,'0')}`;
 add('JOL · '+t('Отчёт о поездке','Сапар есебі'),24);add('Көкшетау → Астана → Алматы',13);if(source)add(source,11);add(trip?t('Период: вся записанная поездка','Кезең: бүкіл жазылған сапар'):t('Период: выбранный момент','Кезең: таңдалған сәт'));add(`${clock(trip?.timeline?.[0]?.time||0)} — ${clock(world.time)} · ${world.time.toFixed(1)} мин`);add(t('Индекс движения: ','Қозғалыс индексі: ')+quality.index+'/100');add(t('Факторы: ','Факторлар: ')+quality.factors.join(' / '));add(t('Выполнено команд: ','Орындалған пәрмендер: ')+world.actions);y-=10;const xs=[42,160,260,380];[t('Поезд','Пойыз'),t('План, мин','Жоспар, мин'),t('Прибыл, мин','Келді, мин'),t('Задержка, мин','Кешігу, мин')].forEach((v,i)=>page.drawText(v,{x:xs[i],y,size:10,font}));y-=25;for(const tr of world.trains){[tr.id,tr.plan.toFixed(1),tr.finished===null?'—':tr.finished.toFixed(1),'+'+tr.delay.toFixed(1)].forEach((v,i)=>page.drawText(v,{x:xs[i],y,size:11,font}));y-=24;}y-=14;add(t('Учебная модель. Нет подключения к системам КТЖ.','Оқу моделі. ҚТЖ жүйелеріне қосылмаған.'),10);add(t('Энергия и расстояния — модельные значения.','Энергия мен қашықтық — модельдік мәндер.'),10);
 const color=s=>{const n=parseInt(s.slice(1),16);return rgb((n>>16&255)/255,(n>>8&255)/255,(n&255)/255);};const line=(points,col,width=1.2)=>{for(let i=1;i<points.length;i++)page.drawLine({start:points[i-1],end:points[i],thickness:width,color:col});};
 if(trip?.timeline?.length){const fs=trip.timeline,min=fs[0].time,max=Math.max(min+1,fs.at(-1).time);newPage();add(t('Поездограмма всей поездки','Бүкіл сапардың пойыз кестесі'),19);add(`${clock(min)} — ${clock(max)} · ${fs.length} `+t('кадров','кадр'),11);const X=n=>120+(n-min)/(max-min)*420,Y=n=>390+n*36;for(let i=0;i<nodes.length;i++){page.drawLine({start:{x:120,y:Y(i)},end:{x:540,y:Y(i)},color:rgb(.85,.88,.9),thickness:.5});page.drawText(nodes[i].name,{x:42,y:Y(i)-3,size:9,font});}for(let f=0;f<=1.001;f+=.25)page.drawText(clock(min+(max-min)*f),{x:110+420*f,y:372,size:9,font});trip.trains.forEach((tr,i)=>{line(fs.map(f=>{const a=f.trains[i];return{x:X(f.time),y:Y(a[1]===null?a[0]:a[1]+a[2])};}),color(tr.color));page.drawText(tr.id,{x:42+(i%3)*174,y:335-Math.floor(i/3)*24,size:11,font,color:color(tr.color)});});
 newPage();add(t('Скорость за всю поездку','Бүкіл сапар жылдамдығы'),19);add(selected+' · '+clock(min)+' — '+clock(max));const idx=trip.trains.findIndex(tr=>tr.id===selected),sx=n=>60+(n-min)/(max-min)*475,sy=v=>470+v/70*225;for(const v of [0,20,40,60]){page.drawLine({start:{x:60,y:sy(v)},end:{x:535,y:sy(v)},thickness:.5,color:rgb(.85,.88,.9)});page.drawText(String(v),{x:40,y:sy(v)-3,font,size:9});}for(const [col,c]of [[8,rgb(.7,.5,.1)],[7,rgb(.05,.6,.45)],[6,rgb(.15,.4,.8)]])line(fs.map(f=>({x:sx(f.time),y:sy(f.trains[idx][col])})),c);for(let f=0;f<=1.001;f+=.25)page.drawText(clock(min+(max-min)*f),{x:50+475*f,y:450,size:9,font});y=420;add(t('Синий — фактическая скорость; зелёный — рекомендация.','Көк — нақты жылдамдық; жасыл — ұсыныс.'),10);add(t('Жёлтый — допустимый предел, км/ч.','Сары — рұқсат етілген шек, км/сағ.'),10);y-=10;add(t('Изменения скорости','Жылдамдық өзгерістері'),14);for(const r of speedChanges(trip,selected)){add(`${clock(r.time)} · ${Math.round(r.actual)} / ${Math.round(r.recommended)} · ${(reasonText[r.reason]||reasonText.cruise)[lang]}`,10);}
 }if(plan){newPage();add(t('Последний прогноз: альтернативы','Соңғы болжам: баламалар'),17);add(t('Момент расчёта: ','Есептеу сәті: ')+clock(plan.start)+` · ${plan.ms.toFixed(1)} ms`);for(const c of plan.candidates)add(`${c.policy.name[lang]}: ${c.metrics.total.toFixed(1)} мин; I=${c.quality.index}`,10);}
 return new Blob([await pdf.save()],{type:'application/pdf'});
}
