import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
export function createScene(host,{tracks=6,name='',lang=0,dark=true,trains=[],onSelect=()=>{},blocked=false}={}){
 let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});}catch(e){host.innerHTML=`<div class="webgl-fallback"><p>${lang?'3D қолжетімсіз. Пойыздар төмендегі таблода көрсетілген.':'3D недоступно в этом браузере. Поезда доступны в табло ниже.'}</p><div class="fallback-tracks">${Array.from({length:tracks},(_,i)=>`<div>${i+1} ━━━━━━━━━━━━━━━━━━━━━</div>`).join('')}</div></div>`;return {update(){},dispose(){},reset(){},top(){}};}
 const scene=new THREE.Scene();scene.background=new THREE.Color(dark?'#101f29':'#e6eef0');scene.fog=new THREE.Fog(scene.background,100,220);
 const camera=new THREE.PerspectiveCamera(38,1,.1,350);camera.position.set(52,58,64);
 renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor(scene.background);host.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label',lang?'Станцияның интерактивті 3D сызбасы':'Интерактивная 3D-схема станции');
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=25;controls.maxDistance=125;controls.maxPolarAngle=Math.PI/2.2;controls.target.set(0,0,0);
 scene.add(new THREE.HemisphereLight(0xd8f8ff,0x354b52,2.3));const sun=new THREE.DirectionalLight(0xffecd6,3);sun.position.set(-25,70,30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-60;sun.shadow.camera.right=60;sun.shadow.camera.top=60;sun.shadow.camera.bottom=-60;scene.add(sun);
 const materials=new Map();const mat=c=>{if(!materials.has(c))materials.set(c,new THREE.MeshStandardMaterial({color:c,roughness:.65,metalness:.14}));return materials.get(c)};
 const box=(w,h,d,c,x,y,z,parent=scene)=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh};
 box(113,.7,tracks*6+30,dark?'#243944':'#b9c9c8',0,-.75,0);
 const grid=new THREE.GridHelper(112,28,dark?0x314752:0x92abab,dark?0x2a424c:0xa8bcbe);grid.position.y=-.34;scene.add(grid);
 function label(text,x,y,z,color='#eaf7f7',scale=1){const c=document.createElement('canvas');c.width=512;c.height=96;const ctx=c.getContext('2d');ctx.fillStyle=dark?'rgba(9,23,31,.9)':'rgba(255,255,255,.95)';ctx.beginPath();ctx.roundRect(3,3,506,90,18);ctx.fill();ctx.font='600 34px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=dark?color:'#163f4b';ctx.fillText(text,256,50);const texture=new THREE.CanvasTexture(c);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,depthTest:false}));s.position.set(x,y,z);s.scale.set(15*scale,2.8*scale,1);scene.add(s);return s;}
 const zs=Array.from({length:tracks},(_,i)=>(i-(tracks-1)/2)*6);
 zs.forEach((z,i)=>{box(100,.15,2.2,dark?'#1b2a31':'#8e9f9f',0,-.05,z);for(let x=-48;x<=48;x+=2)box(.38,.18,2.8,dark?'#455257':'#6e7775',x,.07,z);[-.8,.8].forEach(d=>box(101,.22,.12,'#9eb9bd',0,.25,z+d));label((lang?'Жол ':'Путь ')+(i+1),-48,2,z,'#a3c3cc',.55);if(i<tracks-1&&i%2===0){box(64,.7,2.2,dark?'#57717a':'#c8d5d6',2,.15,z+3);box(64,.04,.14,'#f0c658',2,.53,z+2.03);box(64,.04,.14,'#f0c658',2,.53,z+3.97);for(const x of [-22,0,22]){box(.12,4,.12,'#657d87',x,2.4,z+3);box(5,.2,2.8,dark?'#365d67':'#80a5ae',x,4.5,z+3);}}});
 // Switch connections are illustrative and distinct from the geographic railway map.
 for(let i=1;i<tracks;i++){const points=[new THREE.Vector3(-48,.4,zs[0]),new THREE.Vector3(-38+i*3,.4,zs[i])];scene.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:0x75969c})));}
 const buildingZ=zs[tracks-1]+10;box(30,5,7,dark?'#375a68':'#d1dbdf',2,2,buildingZ);box(32,.5,9,dark?'#1d3e49':'#6c909a',2,4.8,buildingZ);for(let x=-10;x<16;x+=4)box(2.8,2.5,.06,'#73b3c5',x,2.3,buildingZ-3.54);label(name,2,7,buildingZ,'#d2f8f2',1.3);
 let closureObjects=[];if(blocked){closureObjects.push(box(13,.18,tracks*6+1,'#ae4146',31,.2,0));closureObjects.push(label(lang?'УЧАСКЕ ЖАБЫҚ':'УЧАСТОК ЗАКРЫТ',31,6,0,'#ff9996',.9));}
 const trainGroups=[];const clickable=[];
 trains.forEach((data,i)=>{const g=new THREE.Group();const ti=(data.track?data.track-1:i)%tracks;g.position.set(-25+i*9,.35,zs[ti]);scene.add(g);const color=data.color||'#2ac9b2';
 for(let j=0;j<3;j++){const x=-j*6.3;box(5.8,1.75,2,color,x,1.6,0,g);box(5.6,.45,1.85,'#d6e5e9',x,2.66,0,g);box(5.7,.45,2.05,'#30434e',x,.6,0,g);if(j===0)box(.08,1.15,1.55,'#173845',x+2.93,1.92,0,g);
 for(const z of [-1.01,1.01])for(let wx=-1.9;wx<=2;wx+=1.25)box(.83,.68,.03,'#183844',x+wx,1.97,z,g);
 for(const wx of [-1.8,1.8]){const wheel=new THREE.Mesh(new THREE.CylinderGeometry(.42,.42,2.2,10),mat('#17272e'));wheel.rotation.x=Math.PI/2;wheel.position.set(x+wx,.42,0);g.add(wheel);}if(j<2)box(.5,.22,.35,'#8da6ad',x-3.15,.65,0,g);}
 g.traverse(o=>{if(o.isMesh){o.userData.train=data;clickable.push(o);}});const tag=label(data.id,g.position.x-5,5,g.position.z,color,.7);trainGroups.push({g,tag,data,index:i});});
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let pointerStart=null;
 const down=e=>{pointerStart=[e.clientX,e.clientY]};const up=e=>{if(!pointerStart||Math.hypot(e.clientX-pointerStart[0],e.clientY-pointerStart[1])>6)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects(clickable);if(hits[0])onSelect(hits[0].object.userData.train);};renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointerup',up);
 let ended=false,raf;const loop=()=>{if(ended)return;controls.update();renderer.render(scene,camera);raf=requestAnimationFrame(loop)};const resize=()=>{const w=host.clientWidth,h=host.clientHeight;if(w&&h){camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h);}};const observer=new ResizeObserver(resize);observer.observe(host);resize();loop();
 return {update(t,rows=null){closureObjects.forEach(o=>o.visible=t<12);trainGroups.forEach(({g,tag,data,index})=>{let x;if(rows){const r=rows[index];x=t<r.start?-27:t>r.end?43:-27+70*(t-r.start)/r.duration;}else{const arrival=data.arrival??(10+index*9);x=t<arrival?-28+Math.max(0,Math.min(1,t/Math.max(1,arrival)))*26:t<arrival+4?-2:-2+Math.min(1,(t-arrival-4)/12)*45;}g.position.x=x;tag.position.x=x-5;});},reset(){camera.position.set(52,58,64);controls.target.set(0,0,0);controls.update()},top(){camera.position.set(0,90,.01);controls.target.set(0,0,0);controls.update()},dispose(){ended=true;cancelAnimationFrame(raf);observer.disconnect();controls.dispose();scene.traverse(o=>{o.geometry?.dispose();if(o.material?.map)o.material.map.dispose();});materials.forEach(m=>m.dispose());renderer.dispose();host.replaceChildren();}};
}
